apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: speedtest
  namespace: default
spec:
  ingressClassName: traefik
  rules:
    - host: speedtest.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openspeedtest
                port:
                  name: http
