resources:
  - ../../resources/namespaces
  - ../../apps/prometheus-operator/base
  - ../../apps/prometheus/overlays/seattle
  - ../../apps/unbound/overlays/seattle
  - ../../apps/blocky/overlays/seattle
  - ../../apps/traefik/overlays/seattle
  - ../../apps/openspeedtest/base