apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound-config
data:
  unbound.conf: |
    server:
      verbosity: 1
      interface: 0.0.0.0
      port: 53
      do-ip4: yes
      do-udp: yes
      do-tcp: yes
      access-control: 0.0.0.0/0 allow
      module-config: "validator cachedb iterator"
    cachedb:
      backend: "redis"
      redis-server-host: redis.dns.svc.cluster.local
      redis-server-port: 6379
      redis-expire-records: yes
