resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: blocky
    path: patch-replicas.yml
  - target:
      kind: Service
      name: blocky
    path: patch-service-ip.yml
  - target:
      kind: ConfigMap
      name: blocky-config
    path: patch-configmap.yml