namespace: dns

resources:
  - ../../base
  - configmap.yaml

patches:
  - target:
      kind: Deployment
      name: blocky
    path: patch-replicas.yaml
  - target:
      kind: Service
      name: blocky
    path: patch-service-ip.yaml