apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: blocky-pod-monitor
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - dns
  selector:
    matchLabels:
      app: blocky
  podMetricsEndpoints:
    - interval: 30s
      path: /metrics
      port: http
      scheme: http
