apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: networking
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.20
  ports:
    - port: 80
      name: web
      targetPort: 80
    - port: 443
      name: websecure
      targetPort: 443
    - port: 8080
      name: admin
      targetPort: 8080
  selector:
    app: traefik
